- name: Configure Session Timeout
  ansible.builtin.blockinfile:
    dest: /etc/profile
    state: present
    insertbefore: EOF
    marker: "# {mark} MANAGED BY ANSIBLE-HARDENING"
    block: |
      TMOUT={{ session_timeout }}
      readonly TMOUT
      export TMOUT

- name: Disable Ctrl-Alt-Delete 
  ansible.builtin.systemd:
    name: ctrl-alt-del.target
    masked: yes
    enabled: no
